version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - 'C:\STS\001_Websites\002-resume-nginx:/usr/share/nginx/html'